keys:
  - &users:
    - &stepii 1CF624DC518E0BF24858564E2C352F90B4C35A85
  - &hosts:
    - &qemu age1q6ufxuce45g74hmjds0pwcmn94qjp4rpu83any03vgj30a009s2qhp4s5g
creation_rules:
  - path_regex: hosts/qemu/secrets.yaml
    key_groups:
    - age:
      - *qemu
      pgp:
      - *stepii
  - path_regex: hosts/common/secrets.yaml
    key_groups:
    - age:
      - *qemu
      pgp:
      - *stepii
